/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-08-21 13:40:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.User;

public final class seller_002dadd_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/seller-header.jsp", Long.valueOf(1721914390123L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bean.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	User u =null;
	if(session.getAttribute("u") != null){
		u = (User)session.getAttribute("u"); 
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Believe</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='font-awesome/css/font-awesome.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("      \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link href=\"style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Slider -->\r\n");
      out.write("    <link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.transitions.css\" rel=\"stylesheet\"> \r\n");
      out.write("      \r\n");
      out.write("    <!-- lightbox -->\r\n");
      out.write("    <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"wrapper\" class=\"homepage-1\"> <!-- wrapper -->\r\n");
      out.write("          <div id=\"header\"> <!-- header -->\r\n");
      out.write("              <div class=\"top\"> <!-- top -->\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <ul class=\"top-support\"> \r\n");
      out.write("                          <li><i class=\"fa fa-phone-square\"></i><span>(+91) 7016599807</span></li>\r\n");
      out.write("                          <li><a href=\"\"><i class=\"fa fa-envelope-square\"></i><span>info@bootstrapmart.com</span></a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      <div class=\"top-offers\">\r\n");
      out.write("                          <div class=\"alert alert-warning alert-dismissible fade in offers\" role=\"alert\">\r\n");
      out.write("                              <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\"><i class=\"fa fa-times-circle\"></i></span></button>\r\n");
      out.write("                              Free Shipping <a href=\"\">on All Orders Over</a> $75!\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"top-control\">\r\n");
      out.write("                       <a href=\"\">Track Order</a>\r\n");
      out.write("                      ");

                      	if(u != null){
                      		
      out.write("\r\n");
      out.write("                      		<a href=\"profile.jsp\">Profile</a>\r\n");
      out.write("                      		<a href=\"change-password.jsp\">Change Password</a>\r\n");
      out.write("                      		<a href=\"logout.jsp\">Logout&nbsp;(");
      out.print( u.getFname() );
      out.write(")</a>\r\n");
      out.write("                      ");
	}
                      else{
                    	  
      out.write("  \r\n");
      out.write("                    	  <span>•</span><a href=\"register.jsp\">Register</a><span>•\r\n");
      out.write("                          </span><a href=\"login.jsp\">Login</a>\r\n");
      out.write("                    	  \r\n");
      out.write("                      ");
	}
                      
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"clearfix\"></div>\r\n");
      out.write("                      <div class=\"top-offers show-mobile\">\r\n");
      out.write("                          <div class=\"alert alert-warning alert-dismissible fade in offers\" role=\"alert\">\r\n");
      out.write("                              <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\"><i class=\"fa fa-times-circle\"></i></span></button>\r\n");
      out.write("                              Free Shipping <a href=\"\">on All Orders Over</a> $75!\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div> <!-- top -->\r\n");
      out.write("              \r\n");
      out.write("              <div id=\"believe-nav\"> <!-- Nav -->\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <div class=\"min-marg\">\r\n");
      out.write("                          <nav class=\"navbar navbar-default\">\r\n");
      out.write("                              <!-- <div class=\"container-fluid\"> -->\r\n");
      out.write("                                  <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                                  <div class=\"navbar-header\">\r\n");
      out.write("                                      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                                          <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                                          <span class=\"icon-bar\"></span>\r\n");
      out.write("                                          <span class=\"icon-bar\"></span>\r\n");
      out.write("                                          <span class=\"icon-bar\"></span>\r\n");
      out.write("                                      </button>\r\n");
      out.write("                                      <a class=\"navbar-brand\" href=\"seller-index.jsp\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("                                  </div>\r\n");
      out.write("\r\n");
      out.write("                                  <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                                  <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                                      <ul class=\"nav navbar-nav\">\r\n");
      out.write("                                          <li class=\"active\"><a href=\"seller-index.jsp\">Home <span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("                                          <li><a href=\"seller-add-product.jsp\">Add Product</a></li>\r\n");
      out.write("                                          <li><a href=\"seller-view-product.jsp\">View Product</a></li>\r\n");
      out.write("                                          <li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("                                      </ul>                                    \r\n");
      out.write("                                  </div><!-- /.navbar-collapse -->\r\n");
      out.write("                              <!--</div> -->\r\n");
      out.write("                              \r\n");
      out.write("                          </nav>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"srch-form\">\r\n");
      out.write("                          <form class=\"side-search\">\r\n");
      out.write("                              <div class=\"input-group\">\r\n");
      out.write("                                  <input type=\"text\" class=\"form-control search-wid\" placeholder=\"Search Here\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                                  <a href=\"\" class=\"input-group-addon btn-side-serach\" id=\"basic-addon2\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div> <!-- Nav -->\r\n");
      out.write("              \r\n");
      out.write("              <!--<div id=\"cat-nav\">\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <div class=\"wrap-cat\">\r\n");
      out.write("                          <a href=\"#\" id=\"to-open-cat\" class=\"btn btn-default btn-sm\">show categories</a>\r\n");
      out.write("                          <ul class=\"this-cat clearfix\">\r\n");
      out.write("                              <li class=\"active\"><a href=\"\">ELECTRONICS <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">MEN <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">WOMEN <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">BABY & KIDS <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">BOOKS & MEDIA <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">HOME & KITCHEN <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">MORE STORES <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li><a href=\"\">OFFERS ZONE <i class=\"fa fa-angle-down\"></i></a></li>\r\n");
      out.write("                              <li class=\"cat-img-off\"><img src=\"images/offers.png\" alt=\"off\"></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>-->\r\n");
      out.write("              \r\n");
      out.write("              <div id=\"cat-nav\">\r\n");
      out.write("              <div class=\"container\">\r\n");
      out.write("                  <nav class=\"navbar navbar-default\">\r\n");
      out.write("                      <!-- <div class=\"container-fluid\"> -->\r\n");
      out.write("                      <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                      <div class=\"navbar-header\">\r\n");
      out.write("                          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#cat-nav-mega\">\r\n");
      out.write("                              <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                              <span class=\"icon-bar\"></span>\r\n");
      out.write("                              <span class=\"icon-bar\"></span>\r\n");
      out.write("                              <span class=\"icon-bar\"></span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("                      <div class=\"collapse navbar-collapse\" id=\"cat-nav-mega\">\r\n");
      out.write("                          <ul class=\"nav navbar-nav\">\r\n");
      out.write("                              <li class=\"active\"><a href=\"index.jsp\">ELECTRONICS</a></li>\r\n");
      out.write("                              <li class=\"dropdown menu-large\">\r\n");
      out.write("                                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">MEN <i class=\"fa fa-angle-down\"></i></a>\r\n");
      out.write("                                  <ul class=\"dropdown-menu megamenu\" role=\"menu\">\r\n");
      out.write("                                      <li>\r\n");
      out.write("                                          <div class=\"\">\r\n");
      out.write("                                              <div class=\"mega-sub\">\r\n");
      out.write("                                                  <div class=\"mega-sub-title\">All Clothing</div>\r\n");
      out.write("                                                  <ul>\r\n");
      out.write("                                                      <li><a href=\"\">T-Shirts</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Casual & Party Wear Shirts</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Jeans</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Formal Shirts</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Cargos, Shorts & 3/4ths</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Sports Wear</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Trousers</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Suits and Blazers</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Ethnic Wear</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Inner & Sleep Wear</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Accessories</a></li>\r\n");
      out.write("                                                  </ul>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"mega-sub\">\r\n");
      out.write("                                                  <div class=\"mega-sub-title\">All Footwear</div>\r\n");
      out.write("                                                  <ul>\r\n");
      out.write("                                                      <li><a href=\"\">Flats</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Heels</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Bellies</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Wedges</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Slippers & Flip- Flop's</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Sports Shoes</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Sports Sandals</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Casual Shoes</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Formal Shoes</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Ethnic</a></li>\r\n");
      out.write("                                                      <li><a href=\"\">Boots</a></li>\r\n");
      out.write("                                                  </ul>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"mega-product\">\r\n");
      out.write("                                                  <div class=\"mega-sub-title\">Featured products</div>\r\n");
      out.write("                                                  <div class=\"row\">\r\n");
      out.write("                                                      <div class=\"col-md-6 prdct-grid\">\r\n");
      out.write("                                                          <div class=\"product-fade\">\r\n");
      out.write("                                                              <div class=\"product-fade-wrap\">\r\n");
      out.write("                                                                  <div id=\"product-image10\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-9.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-3.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-4.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-5.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-2.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                                  <div class=\"product-fade-ct\">\r\n");
      out.write("                                                                      <div class=\"product-fade-control\">\r\n");
      out.write("                                                                          <div class=\"to-left\">\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-retweet\"></i></a>\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("                                                                          </div>\r\n");
      out.write("                                                                          <div class=\"to-right\">\r\n");
      out.write("                                                                              <div id=\"product-control10\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                              </div>\r\n");
      out.write("                                                                          </div>\r\n");
      out.write("                                                                          <div class=\"clearfix\"></div>\r\n");
      out.write("                                                                          <a href=\"\" class=\"btn btn-to-cart\"><span class=\"bag\"></span><span>Add To cart</span><div class=\"clearfix\"></div></a>\r\n");
      out.write("                                                                      </div>\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                              </div>\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                          <div class=\"product-name\">\r\n");
      out.write("                                                              Striped Men's Round Neck T-Shirt\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                          <div class=\"star-1\"></div>\r\n");
      out.write("                                                          <div class=\"product-price\">\r\n");
      out.write("                                                              <span>$19.00</span> $15.00\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                      <div class=\"col-md-6 prdct-grid\">\r\n");
      out.write("                                                          <div class=\"product-fade\">\r\n");
      out.write("                                                              <div class=\"product-fade-wrap\">\r\n");
      out.write("                                                                  <div id=\"product-image11\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-1.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-3.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-4.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-5.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                      <div class=\"item\"><img src=\"images/p-1.jpg\" alt=\"\" class=\"img-responsive\"></div>\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                                  <div class=\"product-fade-ct\">\r\n");
      out.write("                                                                      <div class=\"product-fade-control\">\r\n");
      out.write("                                                                          <div class=\"to-left\">\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-heart\"></i></a>\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-retweet\"></i></a>\r\n");
      out.write("                                                                              <a href=\"\"><i class=\"fa fa-search\"></i></a>\r\n");
      out.write("                                                                          </div>\r\n");
      out.write("                                                                          <div class=\"to-right\">\r\n");
      out.write("                                                                              <div id=\"product-control11\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                                  <div class=\"item\"><div class=\"bullets\"></div></div>\r\n");
      out.write("                                                                              </div>\r\n");
      out.write("                                                                          </div>\r\n");
      out.write("                                                                          <div class=\"clearfix\"></div>\r\n");
      out.write("                                                                          <a href=\"\" class=\"btn btn-to-cart\"><span class=\"bag\"></span><span>Add To cart</span><div class=\"clearfix\"></div></a>\r\n");
      out.write("                                                                      </div>\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                              </div>\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                          <div class=\"product-name\">\r\n");
      out.write("                                                              Striped Men's Round Neck T-Shirt\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                          <div class=\"star-1\"></div>\r\n");
      out.write("                                                          <div class=\"product-price\">\r\n");
      out.write("                                                              <span>$19.00</span> $15.00\r\n");
      out.write("                                                          </div>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"mega-offers\">\r\n");
      out.write("                                                  <a href=\"\"><img src=\"images/mega-offers.jpg\" class=\"img-responsive\" alt=\"\"></a>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"clearfix\"></div>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li><a href=\"blog.jsp\">WOMEN </a></li>\r\n");
      out.write("                              <li><a href=\"contact.jsp\">BABY & KIDS </a></li>\r\n");
      out.write("                              <li><a href=\"contact.jsp\">BOOKS & MEDIA </a></li>\r\n");
      out.write("                              <li><a href=\"contact.jsp\">HOME & KITCHEN </a></li>\r\n");
      out.write("                              <li><a href=\"contact.jsp\">MORE STORES </a></li>\r\n");
      out.write("                              <li><a href=\"contact.jsp\">OFFERS ZONE </a></li>\r\n");
      out.write("                              <li class=\"cat-img-off\"><img src=\"images/offers.png\" alt=\"off\"></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                           \r\n");
      out.write("                      </div><!-- /.navbar-collapse -->\r\n");
      out.write("                      <!--</div> -->\r\n");
      out.write("                  </nav>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>      \r\n");
      out.write("          </div> <!-- header -->\r\n");
      out.write("      </div> <!-- wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/library.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.raty.js\"></script>\r\n");
      out.write("    <script src=\"js/ui.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.selectbox-0.2.js\"></script>\r\n");
      out.write("    <script src=\"js/theme-script.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Add Products</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='font-awesome/css/font-awesome.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("      \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- main css -->\r\n");
      out.write("    <link href=\"style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Slider -->\r\n");
      out.write("    <link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.theme.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.transitions.css\" rel=\"stylesheet\">\r\n");
      out.write("      \r\n");
      out.write("    <!-- lightbox -->\r\n");
      out.write("    <link href=\"css/prettyPhoto.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"wrapper\" class=\"homepage-1\"> <!-- wrapper -->\r\n");
      out.write("         \r\n");
      out.write("          <div id=\"content\"> <!-- Content -->\r\n");
      out.write("              <div class=\"page-title\">\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <div class=\"page-title-inner\">\r\n");
      out.write("                          <h3>Add Products</h3>\r\n");
      out.write("                          <div class=\"breadcumb\"> <a href=\"\">Home</a><span> / </span><span>Add Products</span></div>\r\n");
      out.write("                          <div class=\"clearfix\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"about-page\">\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-md-8  ct-form\">\r\n");
      out.write("                              <h3>Add Product</h3>\r\n");
      out.write("                              <h2>\r\n");
      out.write("                               <b style=\"color: blue;\">\r\n");
      out.write("                              ");

                              	if(request.getAttribute("msg") != null){
                              		out.println(request.getAttribute("msg"));
                              	}
                              
      out.write("\r\n");
      out.write("                              </b>\r\n");
      out.write("                              </h2>\r\n");
      out.write("                              <form class=\"contact-form\" action=\"ProductController\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                               <div class=\"form-group\">\r\n");
      out.write("                                     <select name=\"product_category\" class=\"form-control\">\r\n");
      out.write("                                     <option>---Select Product Type--</option>\r\n");
      out.write("                                     <option value=\"men\">Men</option>\r\n");
      out.write("                                     <option value=\"women\">Women</option>\r\n");
      out.write("                                     <option value=\"kids\">Kids</option>\r\n");
      out.write("                                     </select>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                      <label for=\"cf_name\">Product Name*</label>\r\n");
      out.write("                                      <input type=\"text\" class=\"form-control\" name=\"product_name\" id=\"fname\" placeholder=\"\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                   <div class=\"form-group\">\r\n");
      out.write("                                      <label for=\"cf_name\">Product Price*</label>\r\n");
      out.write("                                      <input type=\"text\" class=\"form-control\" name=\"product_price\" id=\"lname\" placeholder=\"\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                      <label for=\"cf_email\">Product Image*</label>\r\n");
      out.write("                                      <input type=\"file\" class=\"form-control\" name=\"product_image\" id=\"cf_email\" placeholder=\"\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                      <label for=\"cf_message\">Product Description*</label>\r\n");
      out.write("                                      <textarea class=\"form-control\" name=\"product_desc\" id=\"cf_message\"></textarea>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <button type=\"submit\" name=\"action\" value=\"add product\" class=\"btn btn-blue\">Add Product</button>\r\n");
      out.write("                              </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"map-sec\">\r\n");
      out.write("                          <div class=\"map-sec-wrap\">\r\n");
      out.write("                              <div class=\"add-block\">\r\n");
      out.write("                                  <h3>Believe</h3>\r\n");
      out.write("                                  <p>\r\n");
      out.write("                                      Phone: (941) 364-7748<br/>\r\n");
      out.write("                                      Fax: (941) 364-2322<br/>\r\n");
      out.write("                                      office@yourdomain.com<br/>\r\n");
      out.write("                                      www.yourdomain.com\r\n");
      out.write("                                  </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div id=\"map-canvas\"></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("          </div> <!-- Content -->\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("           <div id=\"footer\"><!-- Footer -->\r\n");
      out.write("              <div class=\"footer-widget\">\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-md-3\">\r\n");
      out.write("                              <div class=\"text-widget\">\r\n");
      out.write("                                  <div class=\"wid-title\">Welcome to</div>\r\n");
      out.write("                                  <img src=\"images/logo-white.png\" alt=\"ft-logo\">\r\n");
      out.write("                                  <p>\r\n");
      out.write("                                      Believe isCommerce WordPress theme. It has<br/>everything you need to start selling today! <a href=\"\">Get this theme on ThemeForest!</a>\r\n");
      out.write("                                  </p>\r\n");
      out.write("                                  <ul class=\"ft-soc clearfix\">\r\n");
      out.write("                                      <li><a href=\"\"><i class=\"fa fa-facebook-square\"></i></a></li>\r\n");
      out.write("                                      <li><a href=\"\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                      <li><a href=\"\"><i class=\"fa fa-google-plus-square\"></i></a></li>\r\n");
      out.write("                                      <li><a href=\"\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                      <li><a href=\"\"><i class=\"fa fa-pinterest\"></i></a></li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                                  <div class=\"clearfix\"></div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-2\">\r\n");
      out.write("                              <div class=\"quick-links\">\r\n");
      out.write("                                  <div class=\"wid-title\">Quick Links</div>\r\n");
      out.write("                                  <ul>\r\n");
      out.write("                                      <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">About US</a></li>\r\n");
      out.write("                                      <li><a href=\"contact.jsp\">contact US</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">deals</a></li>\r\n");
      out.write("                                      <li><a href=\"blog.jsp\">blog</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">help</a></li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-2\">\r\n");
      out.write("                              <div class=\"term\">\r\n");
      out.write("                                  <div class=\"wid-title\">&nbsp;</div>\r\n");
      out.write("                                  <p>\r\n");
      out.write("                                      <a href=\"#\">Tearms & condition</a><br/>\r\n");
      out.write("                                      <a href=\"#\">FAQs</a><br/>\r\n");
      out.write("                                      <a href=\"#\">Privacy Policy</a><br/>\r\n");
      out.write("                                      <a href=\"#\">Legal Desclaimer</a><br/>\r\n");
      out.write("                                  </p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-2\">\r\n");
      out.write("                              <div class=\"quick-links\">\r\n");
      out.write("                                  <div class=\"wid-title\">My Account</div>\r\n");
      out.write("                                  \r\n");
      out.write("                                  <ul>\r\n");
      out.write("                                      <li><a href=\"#\">My Account</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">Personal Information</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">Addresses</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">Orders</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">Wishlist</a></li>\r\n");
      out.write("                                      <li><a href=\"#\">track order</a></li>\r\n");
      out.write("                                  </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col-md-3\">\r\n");
      out.write("                              <div class=\"subscribe\">\r\n");
      out.write("                                  <div class=\"wid-title\">Subscribe for OFFERS & UPDATES</div>\r\n");
      out.write("                                  <p>\r\n");
      out.write("                                      Enter your email and we'll send you a coupon\r\n");
      out.write("                                      with 10% off your next order. Add any text here\r\n");
      out.write("                                  </p>\r\n");
      out.write("                                  <form>\r\n");
      out.write("                                      <div class=\"form-group\">\r\n");
      out.write("                                          <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"Enter email\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                      <button type=\"submit\" class=\"btn btn-default\">Subscribe Now</button>\r\n");
      out.write("                                  </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"footer-text\">\r\n");
      out.write("                  <div class=\"container\">\r\n");
      out.write("                      <p>Copyright 2018. Designed and Developed by <a href=\"https://bootstrapmart.com/\">BootstrapMart </a> &amp; Distributed by <a href=\"https://themewagon.com/\">ThemeWagon</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div><!-- Footer -->\r\n");
      out.write("      </div> <!-- wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/library.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("    <script src=\"js/ui.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.raty.js\"></script>\r\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.selectbox-0.2.js\"></script>\r\n");
      out.write("    <script src=\"js/theme-script.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function initialize() {\r\n");
      out.write("            var mapCanvas = document.getElementById('map-canvas');\r\n");
      out.write("            var mapOptions = {\r\n");
      out.write("                center: new google.maps.LatLng(23.0504397, 72.577511),\r\n");
      out.write("                zoom: 10,\r\n");
      out.write("                disableDefaultUI: true,\r\n");
      out.write("                scrollwheel: false,\r\n");
      out.write("                navigationControl: false,\r\n");
      out.write("                mapTypeControl: false,\r\n");
      out.write("                scaleControl: false,\r\n");
      out.write("                draggable: false,\r\n");
      out.write("                mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("            }\r\n");
      out.write("            var map = new google.maps.Map(mapCanvas, mapOptions)\r\n");
      out.write("            }\r\n");
      out.write("        google.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
