/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-08-22 15:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.bean.User;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1719752791744L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bean.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Carbook - Free Bootstrap 4 Template by Colorlib</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");

    	User u=null;
    	if(session!=null)
    	{
    		if(session.getAttribute("u")!=null)
    		{
    			u=(User)session.getAttribute("u");
    		}
    	}
    
      out.write("\r\n");
      out.write("	  <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("	    <div class=\"container\">\r\n");
      out.write("	      <a class=\"navbar-brand\" href=\"index.jsp\">Car<span>Book</span></a>\r\n");
      out.write("	      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("	        <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("	      </button>\r\n");
      out.write("\r\n");
      out.write("	      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("	        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("	          <li class=\"nav-item active\"><a href=\"index.jsp\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("	          <li class=\"nav-item\"><a href=\"about.jsp\" class=\"nav-link\">About</a></li>\r\n");
      out.write("	          <li class=\"nav-item\"><a href=\"pricing.jsp\" class=\"nav-link\">My Booking</a></li>\r\n");
      out.write("	          <li class=\"nav-item\"><a href=\"car.jsp\" class=\"nav-link\">Cars</a></li>\r\n");
      out.write("	          <li class=\"nav-item\"><a href=\"contact.jsp\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("	          ");

	          	if(u==null)
	          	{
	          
      out.write("\r\n");
      out.write("		          <li class=\"nav-item\"><a href=\"signup.jsp\" class=\"nav-link\">Sign Up</a></li>\r\n");
      out.write("		          <li class=\"nav-item\"><a href=\"login.jsp\" class=\"nav-link\">Login</a></li>\r\n");
      out.write("		      ");

	          	}
	          	else
	          	{
		      
      out.write("\r\n");
      out.write("		      <li class=\"nav-item\"><a href=\"change-password.jsp\" class=\"nav-link\">Change Password</a></li>\r\n");
      out.write("		      <li class=\"nav-item\"><a href=\"logout.jsp\" class=\"nav-link\">Logout</a></li>\r\n");
      out.write("		      ");

	          	}
		      
      out.write("\r\n");
      out.write("	        </ul>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("        <section class=\"hero-wrap hero-wrap-2 js-fullheight\" style=\"background-image: url('images/bg_3.jpg');\" data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row no-gutters slider-text js-fullheight align-items-end justify-content-start\">\r\n");
      out.write("          <div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("          	<p class=\"breadcrumbs\"><span class=\"mr-2\"><a href=\"index.jsp\">Home <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>Contact <i class=\"ion-ios-arrow-forward\"></i></span></p>\r\n");
      out.write("            <h1 class=\"mb-3 bread\">Login</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"ftco-section contact-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row d-flex mb-5 contact-info\">\r\n");
      out.write("        	\r\n");
      out.write("          <div class=\"col-md-12 block-12 mb-md-12\">\r\n");
      out.write("          ");

          		if(request.getAttribute("msg")!=null)
          		{
          			out.println(request.getAttribute("msg"));		
          		}
          	
      out.write("\r\n");
      out.write("            <form name=\"login\" action=\"UserController\" class=\"bg-light p-5 contact-form\" method=\"post\">\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Your Email\" name=\"email\" onblur=\"searchInfo()\">\r\n");
      out.write("                <span id=\"tops\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"submit\" name=\"action\" value=\"Login\" class=\"btn btn-primary py-3 px-5\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("        	<div class=\"col-md-12\">\r\n");
      out.write("        		<div id=\"map\" class=\"bg-white\"></div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\"><a href=\"#\" class=\"logo\">Car<span>book</span></a></h2>\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("              <ul class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4 ml-md-5\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Information</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Services</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Term and Conditions</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Best Price Guarantee</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Privacy &amp; Cookies Policy</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Customer Support</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Payment Option</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Booking Tips</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">How it works</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Contact Us</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("            	<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("            	<div class=\"block-23 mb-3\">\r\n");
      out.write("	              <ul>\r\n");
      out.write("	                <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("	                <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("	                <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("	              </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"js/aos.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("  <script src=\"js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("  <script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"js/main.js\"></script>\r\n");
      out.write("  <script>  \r\n");
      out.write("var request=new XMLHttpRequest();  \r\n");
      out.write("function searchInfo()\r\n");
      out.write("{  \r\n");
      out.write("	var name=document.login.email.value;  \r\n");
      out.write("	var url=\"AjaxSearch2.jsp?val=\"+name;  \r\n");
      out.write("  	try\r\n");
      out.write("  	{  \r\n");
      out.write("		request.onreadystatechange=function()\r\n");
      out.write("		{  \r\n");
      out.write("			if(request.readyState==4)\r\n");
      out.write("			{  \r\n");
      out.write("				var val=request.responseText;\r\n");
      out.write("				document.getElementById('tops').innerHTML=val;\r\n");
      out.write("			}  \r\n");
      out.write("		}  \r\n");
      out.write("		request.open(\"GET\",url,true);  \r\n");
      out.write("		request.send();  \r\n");
      out.write("	}\r\n");
      out.write("  	catch(e)\r\n");
      out.write("  	{\r\n");
      out.write("  		alert(\"Unable to connect to server\");\r\n");
      out.write("  	}  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
